.TH "src/server/helper.h" 3 "Thu Jun 14 2018" "Connected Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/helper.h \- File contains functions used to assist in different tasks\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBproperlyTerminateString\fP (char *string)"
.br
.RI "Replaces the newline character with end of string character\&. "
.in -1c
.SH "Detailed Description"
.PP 
File contains functions used to assist in different tasks\&. 


.PP
\fBDate:\fP
.RS 4
29 May 2018 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void properlyTerminateString (char * string)"

.PP
Replaces the newline character with end of string character\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchar\fP *string: pointer to a char array 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Connected Quiz from the source code\&.
