.TH "src/server/networking.h" 3 "Thu Jun 14 2018" "Connected Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/networking.h \- File contains functions in sending data between client and server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreceiveData\fP (int client_fd, struct sockaddr_in destination, char *buffer)"
.br
.RI "Receives data from the client and puts it in buffer\&. "
.ti -1c
.RI "int \fBsendAndValidate\fP (int client_fd, struct sockaddr_in destination, char *message)"
.br
.RI "Sends the data and waits for verification from the connected client\&. "
.ti -1c
.RI "int \fBhandleClientAnswers\fP (int client_fd, struct sockaddr_in destination, char *correct_answer)"
.br
.RI "Checks the answer that client sends and assign points\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const size_t \fBPORT\fP"
.br
.ti -1c
.RI "const size_t \fBMAX_RECEIVE_BUFFER\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File contains functions in sending data between client and server\&. 


.PP
\fBAuthor:\fP
.RS 4
W3ndige 
.RE
.PP
\fBDate:\fP
.RS 4
29 May 2018 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int handleClientAnswers (int client_fd, struct sockaddr_in destination, char * correct_answer)"

.PP
Checks the answer that client sends and assign points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient_fd\fP File descriptor of client that got accepted\&. 
.br
\fIdestination\fP Structure that contains information about client\&. 
.br
\fIcorrect_answer\fP pointer to correct answer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 when answer is correct, otherwise 0 or -1 on error\&. 
.RE
.PP

.SS "int receiveData (int client_fd, struct sockaddr_in destination, char * buffer)"

.PP
Receives data from the client and puts it in buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient_fd\fP File descriptor of client that got accepted\&. 
.br
\fIdestination\fP Structure that contains information about client\&. 
.br
\fIbuffer\fP pointer to buffer variable\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 on success or 0 on error\&. 
.RE
.PP

.SS "int sendAndValidate (int client_fd, struct sockaddr_in destination, char * message)"

.PP
Sends the data and waits for verification from the connected client\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient_fd\fP File descriptor of client that got accepted\&. 
.br
\fIdestination\fP Structure that contains information about client\&. 
.br
\fImessage\fP pointer to message that is meant to be sent\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 1 on success or 0 on error\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const size_t MAX_RECEIVE_BUFFER"
Maximum buffer that the client can receive\&. 
.SS "const size_t PORT"
Port number of the server client\&.
.PP
Port used in server - client communication\&.
.PP
Port number of the server client\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Connected Quiz from the source code\&.
