.TH "question_info" 3 "Thu Jun 14 2018" "Connected Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
question_info
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcategory_number\fP"
.br
.ti -1c
.RI "char \fBquestion\fP [300]"
.br
.ti -1c
.RI "char \fBanswer_a\fP [100]"
.br
.ti -1c
.RI "char \fBanswer_b\fP [100]"
.br
.ti -1c
.RI "char \fBanswer_c\fP [100]"
.br
.ti -1c
.RI "char \fBanswer_d\fP [100]"
.br
.ti -1c
.RI "char \fBcorrect_answer\fP [2]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int question_info::category_number"
< Structure containing information about question\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Connected Quiz from the source code\&.
