.TH "user_score" 3 "Tue May 29 2018" "Connected Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_score
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpid\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Connected Quiz from the source code\&.
